---
title: "Power analysis: 2021"
output: html_notebook
---

```{r}
rm(list=ls())
library(tidyverse)
library(reshape2)
```
Duration power analysis
```{r}
durations <- read.csv("power_duration_t.csv", header = F)$V1
durations_rep <- rep(durations, 2)
lower <- read.csv("power_duration_1.csv", header = F) %>% 
  t() %>% 
  as.data.frame() %>% 
  melt() %>% 
  mutate(duration=durations_rep) %>% 
  rename(lower=value)
middle <- read.csv("power_duration_2.csv", header = F) %>% 
  t() %>% 
  as.data.frame() %>% 
  melt() %>% 
  mutate(duration=durations_rep) %>% 
  rename(middle=value)
upper <- read.csv("power_duration_3.csv", header = F) %>% 
  t() %>% 
  as.data.frame() %>% 
  melt() %>% 
  mutate(duration=durations_rep) %>% 
  rename(upper=value)

lookup <- tribble(~variable, ~lifespan,
                  "V1", "5 days",
                  "V2", "10 days")

combined <- lower %>%
  left_join(middle) %>% 
  left_join(upper) %>% 
  left_join(lookup)
combined_duration <- combined %>%
  mutate(type="A.")

g1 <- combined %>% 
  ggplot(aes(x=duration, y=middle, colour=lifespan)) +
  geom_pointrange(aes(ymin=lower, ymax=upper)) +
  geom_line() +
  scale_y_log10() +
  xlab("Study duration, days") +
  ylab("RMSE in lifespan estimate") +
  theme(legend.position = c(0.7, 0.83)) +
  scale_color_brewer("True\nlifepan", palette = "Dark2")
```

Release size power analysis
```{r}
durations <- read.csv("power_size_n.csv", header = F)$V1
durations_rep <- rep(durations, 2)
lower <- read.csv("power_size_1.csv", header = F) %>% 
  t() %>% 
  as.data.frame() %>% 
  melt() %>% 
  mutate(duration=durations_rep) %>% 
  rename(lower=value)
middle <- read.csv("power_size_2.csv", header = F) %>% 
  t() %>% 
  as.data.frame() %>% 
  melt() %>% 
  mutate(duration=durations_rep) %>% 
  rename(middle=value)
upper <- read.csv("power_size_3.csv", header = F) %>% 
  t() %>% 
  as.data.frame() %>% 
  melt() %>% 
  mutate(duration=durations_rep) %>% 
  rename(upper=value)

lookup <- tribble(~variable, ~lifespan,
                  "V1", "5 days",
                  "V2", "10 days")

combined <- lower %>%
  left_join(middle) %>% 
  left_join(upper) %>% 
  left_join(lookup)
combined_release <- combined %>%
  mutate(type="B.")

g2 <- combined %>% 
  ggplot(aes(x=duration, y=middle, colour=lifespan)) +
  geom_pointrange(aes(ymin=lower, ymax=upper)) +
  geom_line() +
  scale_y_log10() +
  scale_x_log10() +
  xlab("Release size") +
  ylab("RMSE in lifespan estimate") +
  theme(legend.position = c(0.7, 0.83)) +
  scale_color_brewer("True\nlifepan", palette = "Dark2")
```


```{r}
library(cowplot)
g <- plot_grid(g1, g2, nrow = 1, labels = c("A.", "B."))
```

```{r}
save_plot("../writeUp/Figure_files/mrr_power_analysis.pdf", g)
```


